[package]
name = "installer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
console = "0.15.8"
dialoguer = "0.11.0"
indicatif = "0.17.8"
reqwest = "0.12.8"
serde = "1.0.210"
serde_derive = "1.0.210"
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
