[package]
name = "core"
version = "0.5.2"
edition = "2021"

[[bin]]
name = "rsup"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
command = { version = "0.1.0", path = "../command" }
config = { path = "../config", package = "rsup_config" }
pkg = { path = "../pkg" }
tokio = { version = "1.39.2", features = ["full"] }
web = { path = "../web" }
