[package]
name = "core"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "rsup"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
config = { path = "../config" }
pkg = { path = "../pkg" }
tokio = { version = "1.39.2", features = ["full"] }
web = { path = "../web" }
