[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
pkg = { path = "../pkg" }
tokio = { version = "1.39.2", features = ["full"] }
