[package]
name = "core"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "rsup"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
pkg = { version = "0.1.0", path = "../pkg" }
tokio = { version = "1.39.2", features = ["full"] }
web = { version = "0.1.0", path = "../web" }
