[package]
name = "command"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
config = { version = "0.1.0", path = "../config" }
serde = "1.0.210"
serde_derive = "1.0.210"
tokio = { version = "1.41.0", features = ["full"] }
toml = "0.8.19"
