[package]
name = "command"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
config = { version = "0.1.0", path = "../config" }
reqwest = "0.12.9"
serde = "1.0.210"
serde_derive = "1.0.210"
tokio = { version = "1.41.0", features = ["full"] }
toml = "0.8.19"
rs_utils = { version = "0.1.0", path = "../utils", package = "rsup_utils" }
