[package]
name = "pkg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
semver = "1.0.23"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
tokio = { version = "1.39.2", features = ["full"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
