[package]
name = "pkg"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
config = { path = "../config", package = "rsup_config" }
futures-util = "0.3.30"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
semver = "1.0.23"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
serde_yaml = "0.9.34"
tokio = { version = "1.39.2", features = ["full"] }
rs_utils = { version = "0.1.0", path = "../utils", package = "rsup_utils" }
