[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
once_cell = "1.20.2"
serde = "1.0.210"
serde_derive = "1.0.210"
tokio = { version = "1.41.0", features = ["full"] }
toml = "0.8.19"
