[package]
name = "rsup_utils"
version = "0.1.1"
edition = "2021"
description = "rsup 工具包"
license = "MIT"
authors = ["hboot <bobolity@163.com>"]
keywords = ["rsup", "rs_utils"]
readme = "README.md"
repository = "https://github.com/ngd-b/rsup/tree/main/packages/utils"
homepage = "https://rsup.hboot.fun/api/rsup/utils"
categories = ["command-line-utilities"]

[dependencies]
flate2 = "1.0.35"
futures-util = "0.3.31"
indicatif = "0.17.9"
reqwest = { version = "0.12.9", features = ["stream"] }
serde = "1.0.216"
serde_derive = "1.0.216"
tar = "0.4.43"
tokio = { version = "1.42.0", features = ["full"] }
