name: release

on:
  push:
    tags: "v*" # pushing a tag matching v*. e.g. v1.2.3
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-build:
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/tags') || github.event_name == 'workflow_dispatch'}}
    steps:
      - name: checkout git code
        uses: actions/checkout@v4

      - name: cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install  rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install zip on windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "Installing zip"
          choco install zip -y

      - name: Ensure build.sh is executable
        run: chmod +x build.sh

      - name: build release and create tar.gz for ${{matrix.os}}
        run: bash ./build.sh ${{matrix.os}}

      # - name: list files
      #   run: |
      #     if [[ "${{ matrix.os }}" = "windows-latest" ]]; then
      #       pwsh -Command "Get-ChildItem -Recurse"
      #     else
      #       ls -al
      #     fi
      # - name: Generate changelog
      #   run: |
      #     echo "Generating changelog"
      #     gem install github_changelog_generator
      #     github_changelog_generator -u ngd-b -p rsup

      - run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: create github release
        id: new_release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: latest
          name: ${{github.ref_name}}
          make_latest: true
          files: |
            rsup-${{ matrix.os }}.tar.gz
            rsup-${{ matrix.os }}.zip
            CHANGELOG.md  # 上传生成的 changelog 文件
        # 增加超时时间
        timeout-minutes: 5
